name: Run Merval Bot
on:
  workflow_dispatch:
  schedule:
    - cron: '0 14 * * 1-5'  # 11:00 Arg
    - cron: '0 15 * * 1-5'  # 12:00 Arg
    - cron: '0 16 * * 1-5'  # 13:00 Arg
    - cron: '0 17 * * 1-5'  # 14:00 Arg
    - cron: '0 18 * * 1-5'  # 15:00 Arg
    - cron: '0 19 * * 1-5'  # 16:00 Arg
    - cron: '0 20 * * 1-5'  # 17:00 Arg
    - cron: '0 21 * * 1-5'  # 18:00 Arg

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v4
      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Instalar dependencias
        run: |
          pip install yfinance requests pytz pandas
      - name: Ejecutar Script Merval
        env:
          TOKEN_BOT: ${{ secrets.TOKEN_BOT }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: python bot_merval.py  # ← corregido, era .yml
