name: Run Merval Bot

on:
  workflow_dispatch:   # lo podés lanzar manualmente
  schedule:
          - cron: '50 13 * * 1-5'   # apertura 10:50 Arg
          - cron: '5 14 * * 1-5'    # 11:05 Arg
          - cron: '0 15,16,17,18,19,20,21 * * 1-5' # alertas horarias

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v4   # actualizado

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar dependencias
        run: |
          pip install yfinance requests pytz pandas

      - name: Ejecutar Script Merval
        env:
          TOKEN_BOT: ${{ secrets.TOKEN_BOT }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: python bot_merval.py
